POST http://localhost:8000/jira/query
Content-Type: application/json

{
  "user": "alice@example.com",
  "intent": "get_jira_issues",
  "parameters": {
    "project": ["AS"],
    "created_after": "-1w",
    "created_before": "-1d",
    "only_count": false
  }
}


