POST http://localhost:8000/jira/query
Content-Type: application/json

{
  "user": "jaroslav",
  "intent": "update_project_charter",
  "parameters": {
    "ticket": "DELTP-7867",
    "update_instruction": "Remove the Project start date"
  }
}
