services:
  mcp-jira-server:
    build: .
    container_name: mcp-jira-server
    ports:
      - "8005:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - supabase_default

networks:
  supabase_default:
    external: true
